# Generated by Django 5.1.4 on 2025-01-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='manage_order_type',
            field=models.CharField(choices=[('Subscription', 'Subscription Orders'), ('Product', 'Product Orders'), ('Both', 'Both Subscription and Product Orders')], default='Product', help_text='Specify if the employee manages Subscription or Product orders.', max_length=20),
        ),
    ]
