# Generated by Django 5.1.4 on 2025-01-01 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_pincodearea_carddetails_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pincodearea',
            name='pincode',
            field=models.CharField(max_length=6),
        ),
    ]
