# Generated by Django 5.1.4 on 2025-01-01 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_carddetails_expiry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carddetails',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='carddetails',
            name='cvv',
        ),
        migrations.AddField(
            model_name='carddetails',
            name='card_number_encrypted',
            field=models.BinaryField(default=b''),
        ),
        migrations.AddField(
            model_name='carddetails',
            name='cvv_encrypted',
            field=models.BinaryField(default=b''),
        ),
        migrations.AlterField(
            model_name='carddetails',
            name='expiry_date',
            field=models.DateField(),
        ),
    ]
