# Generated by Django 5.1.4 on 2025-01-01 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_carddetails_expiry_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CardDetails',
            new_name='CardDetailss',
        ),
    ]
