# Generated by Django 5.1.4 on 2025-01-01 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_rename_carddetails_carddetailss'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CardDetailss',
            new_name='CardDetails',
        ),
    ]
