# Generated by Django 5.1.4 on 2025-01-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_rename_carddetailss_carddetails'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(fields=('user', 'pincode_area', 'address'), name='unique_user_address'),
        ),
    ]
