# Generated by Django 5.1.4 on 2024-12-25 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Basic', 'Basic Plan'), ('Standard', 'Standard Plan'), ('Premium', 'Premium Plan')], help_text='Name of the subscription plan', max_length=20)),
                ('price_per_month', models.DecimalField(decimal_places=2, help_text='Monthly cost of the subscription', max_digits=10)),
                ('milk_quantity_per_day', models.DecimalField(decimal_places=2, help_text='Amount of milk provided daily (in liters)', max_digits=5)),
                ('discount_on_byproducts', models.PositiveIntegerField(help_text='Discount percentage on byproducts (e.g., ghee, butter)')),
                ('delivery_pause_limit', models.PositiveIntegerField(help_text='Maximum number of days per month delivery can be paused')),
            ],
        ),
    ]
