# Generated by Django 5.1.4 on 2024-12-25 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(help_text='Name of the user providing the feedback', max_length=100)),
                ('feedback', models.TextField(help_text="User's feedback about the subscription plan")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(help_text='The subscription plan this feedback is for', on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='subscriptions.subscriptionplan')),
            ],
        ),
    ]
