# Generated by Django 5.1.4 on 2024-12-31 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscriptionfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
