# Generated by Django 5.1.4 on 2025-02-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_product_remove_order_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
