# Generated by Django 5.1.4 on 2024-12-25 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('unit', models.CharField(choices=[('ml', 'Milliliters (ml)'), ('l', 'Liters (l)'), ('mg', 'Milligrams (mg)'), ('gm', 'Grams (gm)')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_in_stock', models.BooleanField(default=True)),
                ('image', models.ImageField(default='products/default.jpg', upload_to='products/images/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('subscription_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.subscriptionplan')),
                ('variants', models.ManyToManyField(to='products.variant')),
            ],
        ),
    ]
