# Generated by Django 5.1.4 on 2024-12-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_nutrientfact'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='nutrient_facts',
            field=models.JSONField(default=dict),
        ),
        migrations.DeleteModel(
            name='NutrientFact',
        ),
    ]
