# Generated by Django 5.1.4 on 2024-12-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_nutrient_facts_delete_nutrientfact'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='benefits_image',
            field=models.JSONField(default=dict),
        ),
    ]
