# Generated by Django 5.1.4 on 2024-12-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_benefits_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
