# Generated by Django 5.1.4 on 2024-12-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_product_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_video',
            field=models.FileField(blank=True, null=True, upload_to='products/videos/'),
        ),
    ]
