# Generated by Django 5.1.4 on 2024-12-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_product_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='variants',
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('ml', 'Milliliters (ml)'), ('l', 'Liters (l)'), ('mg', 'Milligrams (mg)'), ('gm', 'Grams (gm)')], default='ml', max_length=2),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Variant',
        ),
    ]
