# Generated by Django 5.1.4 on 2025-03-07 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_product_is_in_stock_product_quantity'),
        ('subscriptions', '0003_alter_subscriptionplan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='subscription_plan',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.subscriptionplan'),
        ),
    ]
